default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: datalogger_dev

test:
  <<: *default
  database: datalogger_test

production:
  <<: *default
  database: datalogger_prod
